[info]
year = "2021"
major_code = "030202"
major_name = "自动化（第二学士学位）"
school_name = "机器人与先进制造学院"
plan_ID = "C6FEABD2F5737492E0530C18F80A0D42"

[[courses]]
course_code = "AUTO2005"
credit = 2.5
assessment_method = "考试"
course_name = "信号分析与处理"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 40

[courses.hours]
theory = 32
lab = 4
practice = 0
exercise = 0
computer = 4
tutoring = 0
[[courses]]
course_code = "AUTO3001A"
credit = 4.5
assessment_method = "考试"
course_name = "自动控制理论A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 76

[courses.hours]
theory = 64
lab = 8
practice = 0
exercise = 0
computer = 4
tutoring = 0
[[courses]]
course_code = "AUTO3002A"
credit = 3.0
assessment_method = "考试"
course_name = "自动控制实践A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3003"
credit = 2.0
assessment_method = "考查"
course_name = "数字图像处理"
recommended_year_semester = "第一学年秋季"
track = "智能检测模块-智能检测模块必选,智能检测模块-智能检测必选,智能检测模块-智能检测模块必选"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 36

[courses.hours]
theory = 28
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3004"
credit = 2.5
assessment_method = "考查"
course_name = "系统建模与仿真"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 40

[courses.hours]
theory = 32
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3016"
credit = 1.0
assessment_method = "考查"
course_name = "自动控制实践A课程设计"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 0

[courses.hours]
theory = 0
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO2006"
credit = 2.5
assessment_method = "考试"
course_name = "控制理论中的代数基础"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3001B"
credit = 5.0
assessment_method = "考试"
course_name = "自动控制理论B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 80

[courses.hours]
theory = 64
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3002B"
credit = 6.0
assessment_method = "考试"
course_name = "自动控制实践B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 96

[courses.hours]
theory = 56
lab = 40
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3005"
credit = 2.0
assessment_method = "考查"
course_name = "机器人学导论"
recommended_year_semester = "第一学年春季"
track = "机器人与智能系统模块-机器人模块必选,机器人与智能系统模块-机器人模块必选,机器人与智能系统模块-机器人模块必选"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 36

[courses.hours]
theory = 28
lab = 0
practice = 8
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3006"
credit = 2.0
assessment_method = "考查"
course_name = "机器视觉"
recommended_year_semester = "第一学年春季"
track = "智能检测模块-智能检测模块选修,智能检测模块-智能检测模块选修,智能检测模块-智能检测选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3007"
credit = 3.0
assessment_method = "考查"
course_name = "过程控制系统"
recommended_year_semester = "第一学年春季"
track = "控制理论与控制工程模块-控制模块必选,控制理论与控制工程模块-控制模块必选,控制理论与控制工程模块-控制模块必选"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH3010"
credit = 3.0
assessment_method = "考查"
course_name = "数学规划"
recommended_year_semester = "第一学年春季"
track = "控制理论与控制工程模块-控制模块必选,控制理论与控制工程模块-控制模块必选,控制理论与控制工程模块-控制模块必选"
course_nature = "限选"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3009"
credit = 2.0
assessment_method = "考查"
course_name = "先进控制概论"
recommended_year_semester = "第二学年秋季"
track = "控制理论与控制工程模块-控制模块选修,控制理论与控制工程模块-控制模块选修,控制理论与控制工程模块-控制模块选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3010"
credit = 2.0
assessment_method = "考查"
course_name = "集散控制系统与组态元件"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3011"
credit = 2.0
assessment_method = "考查"
course_name = "运动控制系统"
recommended_year_semester = "第二学年秋季"
track = "机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3012"
credit = 2.0
assessment_method = "考查"
course_name = "移动机器人导论"
recommended_year_semester = "第二学年秋季"
track = "机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3013"
credit = 2.0
assessment_method = "考查"
course_name = "智能控制"
recommended_year_semester = "第二学年秋季"
track = "控制理论与控制工程模块-控制模块选修,控制理论与控制工程模块-控制模块选修,控制理论与控制工程模块-控制模块选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 36

[courses.hours]
theory = 28
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3014"
credit = 2.0
assessment_method = "考查"
course_name = "自动化前沿专题"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3018"
credit = 2.0
assessment_method = "考查"
course_name = "人工智能基础"
recommended_year_semester = "第二学年秋季"
track = "智能检测模块-智能检测模块选修,智能检测模块-智能检测模块选修,智能检测模块-智能检测选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3019"
credit = 2.0
assessment_method = "考查"
course_name = "机器学习概论"
recommended_year_semester = "第二学年秋季"
track = "机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修,机器人与智能系统模块-机器人模块选修"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3007"
credit = 2.0
assessment_method = "考查"
course_name = "模式识别"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3099"
credit = 10.0
assessment_method = "考查"
course_name = "毕业设计"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 0

[courses.hours]
theory = 640
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
