[[courses]]
course_code = "EE1007"
credit = 3.5
assessment_method = "考试"
course_name = "模拟电子技术基础"
recommended_year_semester = "第一学年秋季"
track = "专业基础课（技术基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 56

[courses.hours]
theory = 56
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1008"
credit = 1.0
assessment_method = "考查"
course_name = "模拟电子技术实验"
recommended_year_semester = "第一学年秋季"
track = "专业基础课（技术基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3005"
credit = 3.5
assessment_method = "考试"
course_name = "电磁场与电磁波"
recommended_year_semester = "第一学年秋季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 56

[courses.hours]
theory = 48
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1001A"
credit = 5.0
assessment_method = "考试"
course_name = "高等数学A"
recommended_year_semester = "第一学年秋季"
track = "数学与自然科学基础课"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
track = "数学与自然科学基础课"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 2.5
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第一学年秋季"
track = "数学与自然科学基础课"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1005"
credit = 2.5
assessment_method = "考试"
course_name = "复变函数与积分变换"
recommended_year_semester = "第一学年秋季"
track = "数学与自然科学基础课"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1009"
credit = 3.5
assessment_method = "考试"
course_name = "数字电子技术基础"
recommended_year_semester = "第一学年春季"
track = "专业基础课（技术基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 56

[courses.hours]
theory = 56
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1010"
credit = 1.0
assessment_method = "考查"
course_name = "数字电子技术实验"
recommended_year_semester = "第一学年春季"
track = "专业基础课（技术基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2002"
credit = 3.0
assessment_method = "考试"
course_name = "信号与系统"
recommended_year_semester = "第一学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2003"
credit = 1.0
assessment_method = "考查"
course_name = "信号与系统实验"
recommended_year_semester = "第一学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2005"
credit = 3.0
assessment_method = "考试"
course_name = "通信电子线路"
recommended_year_semester = "第一学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2006"
credit = 1.0
assessment_method = "考查"
course_name = "通信电子线路实验"
recommended_year_semester = "第一学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3008"
credit = 3.0
assessment_method = "考试"
course_name = "随机信号分析"
recommended_year_semester = "第一学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1001B"
credit = 5.0
assessment_method = "考试"
course_name = "高等数学B"
recommended_year_semester = "第一学年春季"
track = "数学与自然科学基础课"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2007"
credit = 2.0
assessment_method = "考查"
course_name = "课程设计A：通信基础电路设计"
recommended_year_semester = "第一学年夏季"
track = "实习实训"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 0

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3017"
credit = 2.0
assessment_method = "考查"
course_name = "FPGA设计与应用"
recommended_year_semester = "第一学年夏季"
track = "实习实训"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 0
lab = 48
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3001"
credit = 3.0
assessment_method = "考试"
course_name = "通信原理"
recommended_year_semester = "第二学年秋季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3003"
credit = 3.0
assessment_method = "考试"
course_name = "数字信号处理"
recommended_year_semester = "第二学年秋季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3014"
credit = 2.0
assessment_method = "考查"
course_name = "生物医学电子"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3019"
credit = 2.0
assessment_method = "考查"
course_name = "通信安全"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3021"
credit = 2.0
assessment_method = "考查"
course_name = "无线通信网"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 20
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3023"
credit = 2.0
assessment_method = "考查"
course_name = "空间通信"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3025"
credit = 2.0
assessment_method = "考查"
course_name = "微波与天线"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3026"
credit = 2.0
assessment_method = "考查"
course_name = "卫星通信"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3028"
credit = 2.0
assessment_method = "考查"
course_name = "模式识别"
recommended_year_semester = "第二学年秋季"
track = "专业选修课"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3007"
credit = 2.0
assessment_method = "考查"
course_name = "扩频通信"
recommended_year_semester = "第二学年春季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3011"
credit = 3.0
assessment_method = "考试"
course_name = "移动通信"
recommended_year_semester = "第二学年春季"
track = "专业必修课"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3015"
credit = 2.0
assessment_method = "考查"
course_name = "可见光通信"
recommended_year_semester = "第二学年春季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3016"
credit = 2.0
assessment_method = "考查"
course_name = "工程管理学"
recommended_year_semester = "第二学年春季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3029"
credit = 2.0
assessment_method = "考查"
course_name = "图象处理"
recommended_year_semester = "第二学年春季"
track = "专业选修课"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3099"
credit = 10.0
assessment_method = "考查"
course_name = "毕业设计（论文）"
recommended_year_semester = "第二学年春季"
track = "毕业设计（论文）"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 0

[courses.hours]
theory = 480
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
