[info]
year = "2023"
major_code = "070201F"
major_name = "工商管理"
school_name = "经济管理学院"
plan_ID = "037F0B9CC2442B20E0630B18F80A2FE4"

[[courses]]
course_code = "HUMA1110E"
credit = 2.0
assessment_method = "考查"
course_name = "中国概况"
recommended_year_semester = "第一学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1113E"
credit = 2.0
assessment_method = "考查"
course_name = "中国式现代化：研究与探索"
recommended_year_semester = "第一学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1120E"
credit = 3.0
assessment_method = "考查"
course_name = "初级汉语I"
recommended_year_semester = "第一学年秋季"
track = "公共基础课程-中文课"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002E"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
track = "公共基础课程-数理与自然科学基础课程"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015AE"
credit = 5.0
assessment_method = "考试"
course_name = "微积分A"
recommended_year_semester = "第一学年秋季"
track = "公共基础课程-数理与自然科学基础课程"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1111E"
credit = 2.0
assessment_method = "考查"
course_name = "中国文化"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1114E"
credit = 2.0
assessment_method = "考查"
course_name = "中国碳达峰、碳中和目标的实现路径"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1119E"
credit = 1.0
assessment_method = "考查"
course_name = "考古与中华文明"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 12
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1121E"
credit = 3.0
assessment_method = "考查"
course_name = "初级汉语 II"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-中文课"
course_nature = "必修"
course_category = "其他"
offering_college = "人文艺术学系"
total_hours = 48

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 24
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1124E"
credit = 1.0
assessment_method = "考查"
course_name = "中国典型滨海湿地的退化与保护"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 6
lab = 0
practice = 10
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015BE"
credit = 5.0
assessment_method = "考试"
course_name = "微积分B"
recommended_year_semester = "第一学年春季"
track = "公共基础课程-数理与自然科学基础课程"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1118E"
credit = 1.0
assessment_method = "考查"
course_name = "中国传统服饰与印染"
recommended_year_semester = "第一学年春季,第二学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 8
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "BIO1002E"
credit = 2.0
assessment_method = "考试"
course_name = "生命与健康科学"
recommended_year_semester = "第二学年秋季"
track = "公共基础课程-数理与自然科学基础课程"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2030E"
credit = 2.0
assessment_method = "考试"
course_name = "高级语言程序设计"
recommended_year_semester = "第二学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 8
tutoring = 0
[[courses]]
course_code = "ECON1001E"
credit = 2.0
assessment_method = "考查"
course_name = "经济管理专业导论"
recommended_year_semester = "第二学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2008E"
credit = 2.0
assessment_method = "考试"
course_name = "微观经济学"
recommended_year_semester = "第二学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2010E"
credit = 3.0
assessment_method = "考试"
course_name = "基础计量经济学"
recommended_year_semester = "第二学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1122E"
credit = 2.0
assessment_method = "考查"
course_name = "中级汉语 I"
recommended_year_semester = "第二学年秋季"
track = "公共基础课程-中文课"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1125E"
credit = 2.0
assessment_method = "考查"
course_name = "中国土木工程材料及其结构应用"
recommended_year_semester = "第二学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 32

[courses.hours]
theory = 28
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1126E"
credit = 2.0
assessment_method = "考查"
course_name = "中国制造的复兴之路"
recommended_year_semester = "第二学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004E"
credit = 3.0
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
track = "公共基础课程-数理与自然科学基础课程"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1127E"
credit = 1.0
assessment_method = "考查"
course_name = "中国古典园林鉴赏"
recommended_year_semester = "第二学年秋季,第二学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 10
lab = 6
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ACCT2002E"
credit = 2.0
assessment_method = "考试"
course_name = "会计学原理"
recommended_year_semester = "第二学年春季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2028E"
credit = 2.0
assessment_method = "考试"
course_name = "国际金融"
recommended_year_semester = "第二学年春季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3063E"
credit = 2.0
assessment_method = "考试"
course_name = "商业伦理"
recommended_year_semester = "第二学年春季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1112E"
credit = 1.0
assessment_method = "考查"
course_name = "中国文学"
recommended_year_semester = "第二学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文艺术学系"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1123E"
credit = 2.0
assessment_method = "考查"
course_name = "中级汉语 II"
recommended_year_semester = "第二学年春季"
track = "公共基础课程-中文课"
course_nature = "必修"
course_category = "其他"
offering_college = "人文艺术学系"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1129E"
credit = 1.0
assessment_method = "考查"
course_name = "中国清洁空气行动与应对气候变化"
recommended_year_semester = "第二学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "生态环境学院"
total_hours = 16

[courses.hours]
theory = 10
lab = 2
practice = 4
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1130E"
credit = 2.0
assessment_method = "考查"
course_name = "中国先进结构建造和监测技术"
recommended_year_semester = "第二学年春季"
track = "公共基础课程-国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2032E"
credit = 3.0
assessment_method = "考查"
course_name = "夏季暑期实习（认知实习）"
recommended_year_semester = "第二学年夏季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 120

[courses.hours]
theory = 0
lab = 0
practice = 3
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ACCT2005E"
credit = 2.0
assessment_method = "考试"
course_name = "财务管理"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2019E"
credit = 2.0
assessment_method = "考试"
course_name = "宏观经济学"
recommended_year_semester = "第三学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2031E"
credit = 2.0
assessment_method = "考查"
course_name = "经济管理前沿讲座"
recommended_year_semester = "第三学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2033E"
credit = 2.0
assessment_method = "考查"
course_name = "国际贸易"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2034E"
credit = 2.0
assessment_method = "考查"
course_name = "中国经济专题"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2038E"
credit = 2.0
assessment_method = "考试"
course_name = "运营管理"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2039E"
credit = 2.0
assessment_method = "考试"
course_name = "战略管理"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3001E"
credit = 2.0
assessment_method = "考查"
course_name = "博弈论"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3067E"
credit = 2.0
assessment_method = "考试"
course_name = "组织行为学"
recommended_year_semester = "第三学年秋季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1132E"
credit = 1.0
assessment_method = "考查"
course_name = "中国建筑欣赏"
recommended_year_semester = "第三学年秋季"
track = "公共基础课程-国情类课程"
course_nature = "选修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 12
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2030E"
credit = 3.0
assessment_method = "考查"
course_name = "经济管理研究方法"
recommended_year_semester = "第三学年春季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2069E"
credit = 2.0
assessment_method = "考查"
course_name = "数字经济学"
recommended_year_semester = "第三学年春季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3016E"
credit = 2.0
assessment_method = "考查"
course_name = "环境经济学"
recommended_year_semester = "第三学年春季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3068E"
credit = 2.0
assessment_method = "考试"
course_name = "人力资源管理"
recommended_year_semester = "第三学年春季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3072E"
credit = 2.0
assessment_method = "考试"
course_name = "市场营销学"
recommended_year_semester = "第三学年春季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2035E"
credit = 3.0
assessment_method = "考查"
course_name = "夏季暑期实习（实践实习）"
recommended_year_semester = "第三学年夏季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 120

[courses.hours]
theory = 0
lab = 0
practice = 3
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2029E"
credit = 2.0
assessment_method = "考试"
course_name = "大数据与商业分析"
recommended_year_semester = "第四学年秋季"
track = "大类平台课程（大类专业基础课）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2036E"
credit = 6.0
assessment_method = "考查"
course_name = "专业实习"
recommended_year_semester = "第四学年秋季"
track = "专业方向课程-专业方向核心课程（必修）"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 240

[courses.hours]
theory = 0
lab = 0
practice = 6
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2037E"
credit = 2.0
assessment_method = "考查"
course_name = "绿色金融导论"
recommended_year_semester = "第四学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON2040E"
credit = 2.0
assessment_method = "考查"
course_name = "管理信息系统"
recommended_year_semester = "第四学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3036E"
credit = 1.0
assessment_method = "考查"
course_name = "资本论选读"
recommended_year_semester = "第四学年秋季"
track = "专业方向课程-专业方向选修课程"
course_nature = "选修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ACCT3099E"
credit = 10.0
assessment_method = "考查"
course_name = "毕业设计"
recommended_year_semester = "第四学年春季"
track = "专业方向课程-毕业论文"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 400

[courses.hours]
theory = 0
lab = 0
practice = 10
exercise = 0
computer = 0
tutoring = 0
