[info]
year = "2023"
major_code = "0103"
major_name = "人工智能班"
school_name = "计算机科学与技术学院"
plan_ID = "17D93F89463DEB95E0630C18F80A842E"

[[courses]]
course_code = "AISZ1005"
credit = 3.0
assessment_method = "考查"
course_name = "数据结构与算法"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ1006"
credit = 4.0
assessment_method = "考试"
course_name = "离散数学"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2001"
credit = 3.0
assessment_method = "考试"
course_name = "机器学习"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ3001"
credit = 2.0
assessment_method = "考查"
course_name = "专项研讨课"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 0
lab = 0
practice = 32
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ3002"
credit = 2.0
assessment_method = "考查"
course_name = "基础项目实践"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 240

[courses.hours]
theory = 0
lab = 0
practice = 6
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1011"
credit = 3.0
assessment_method = "考试"
course_name = "马克思主义基本原理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 3.0
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1005"
credit = 2.0
assessment_method = "考查"
course_name = "复变函数与积分变换"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002C"
credit = 0.5
assessment_method = "考查"
course_name = "体育C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1009"
credit = 2.0
assessment_method = "考查"
course_name = "量子物理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2002"
credit = 3.0
assessment_method = "考试"
course_name = "计算机系统"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2005"
credit = 3.0
assessment_method = "考查"
course_name = "计算机视觉"
recommended_year_semester = "第二学年春季"
track = "二选一"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2006"
credit = 3.0
assessment_method = "考查"
course_name = "自然语言处理"
recommended_year_semester = "第二学年春季"
track = "二选一"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE2005"
credit = 3.0
assessment_method = "考试"
course_name = "系统与控制"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 8
practice = 0
exercise = 0
computer = 4
tutoring = 0
[[courses]]
course_code = "ELEC2018"
credit = 3.5
assessment_method = "考查"
course_name = "信号与系统"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 64

[courses.hours]
theory = 48
lab = 8
practice = 8
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENGG1003"
credit = 2.0
assessment_method = "考查"
course_name = "工程训练（电子工艺实习）"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 0

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1018"
credit = 2.5
assessment_method = "考试"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-2"
credit = 1.0
assessment_method = "考查"
course_name = "形势与政策-2"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002D"
credit = 0.5
assessment_method = "考查"
course_name = "体育D"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "WRIT0001"
credit = 1.0
assessment_method = "考查"
course_name = "写作与沟通"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "世界文明与对话"
offering_college = "人文与社会科学学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2007"
credit = 2.0
assessment_method = "考查"
course_name = "企业认知实习"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ1007"
credit = 2.0
assessment_method = "考查"
course_name = "人工智能前沿讲座"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3002A"
credit = 3.0
assessment_method = "考查"
course_name = "自动控制实践A"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-自动化方向"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3016"
credit = 1.5
assessment_method = "考查"
course_name = "自动控制实践A实验"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-自动化方向"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 40

[courses.hours]
theory = 0
lab = 40
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3010"
credit = 3.0
assessment_method = "考查"
course_name = "数据库系统"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-计算机科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3059"
credit = 2.5
assessment_method = "考查"
course_name = "软件构造"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-计算机科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 24
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2005"
credit = 3.5
assessment_method = "考查"
course_name = "通信电子线路"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-信息科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 56

[courses.hours]
theory = 40
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3066"
credit = 3.0
assessment_method = "考查"
course_name = "电磁波与天线理论"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-信息科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH3005"
credit = 3.0
assessment_method = "考查"
course_name = "机电系统控制基础"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-机器人工程方向"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH3060"
credit = 2.0
assessment_method = "考查"
course_name = "机器人学基础"
recommended_year_semester = "第三学年秋季"
track = "方向选修课-机器人工程方向"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 28
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002E"
credit = 0.5
assessment_method = "考查"
course_name = "体育E"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "AISZ3003"
credit = 4.0
assessment_method = "考查"
course_name = "创新研究与项目实践"
recommended_year_semester = "第三学年秋季,第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 400

[courses.hours]
theory = 0
lab = 0
practice = 10
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ2004"
credit = 2.0
assessment_method = "考试"
course_name = "信息论"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3001B"
credit = 4.5
assessment_method = "考查"
course_name = "自动控制理论B"
recommended_year_semester = "第三学年春季"
track = "方向选修课-自动化方向"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 72

[courses.hours]
theory = 60
lab = 8
practice = 0
exercise = 0
computer = 4
tutoring = 0
[[courses]]
course_code = "AUTO3002B"
credit = 4.0
assessment_method = "考查"
course_name = "自动控制实践B"
recommended_year_semester = "第三学年春季"
track = "方向选修课-自动化方向"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 64

[courses.hours]
theory = 48
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3001"
credit = 4.0
assessment_method = "考试"
course_name = "操作系统"
recommended_year_semester = "第三学年春季"
track = "方向选修课-计算机科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 40
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3057"
credit = 3.0
assessment_method = "考查"
course_name = "计算机网络"
recommended_year_semester = "第三学年春季"
track = "方向选修课-计算机科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3001"
credit = 3.0
assessment_method = "考查"
course_name = "通信原理"
recommended_year_semester = "第三学年春季"
track = "方向选修课-信息科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3003"
credit = 3.0
assessment_method = "考查"
course_name = "数字信号处理"
recommended_year_semester = "第三学年春季"
track = "方向选修课-信息科学与技术方向"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-3"
credit = 0.5
assessment_method = "考查"
course_name = "形势与政策-3"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH3062"
credit = 2.0
assessment_method = "考查"
course_name = "机器人系统综合课程设计"
recommended_year_semester = "第三学年春季"
track = "方向选修课-机器人工程方向"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH3063"
credit = 2.0
assessment_method = "考查"
course_name = "机器人机构学"
recommended_year_semester = "第三学年春季"
track = "方向选修课-机器人工程方向"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH3064"
credit = 2.0
assessment_method = "考查"
course_name = "机器人运动控制技术"
recommended_year_semester = "第三学年春季"
track = "方向选修课-机器人工程方向"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002F"
credit = 0.5
assessment_method = "考查"
course_name = "体育F"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "AISZ2008"
credit = 2.0
assessment_method = "考查"
course_name = "产业创新实习"
recommended_year_semester = "第三学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AISZ3099"
credit = 8.0
assessment_method = "考查"
course_name = "毕业论文（设计）"
recommended_year_semester = "第四学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 640

[courses.hours]
theory = 0
lab = 0
practice = 16
exercise = 0
computer = 0
tutoring = 0
