[[courses]]
course_code = "CHEM1007"
credit = 2.0
assessment_method = "考查"
course_name = "大学化学II"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP1010"
credit = 2.0
assessment_method = "考查"
course_name = "C语言程序设计II"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1014"
credit = 2.0
assessment_method = "考查"
course_name = "思想政治理论实践课"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 32

[courses.hours]
theory = 8
lab = 0
practice = 24
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1015"
credit = 2.5
assessment_method = "考查"
course_name = "思想道德与法治"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1017"
credit = 2.5
assessment_method = "考查"
course_name = "习近平新时代中国特色社会主义思想概论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1006"
credit = 1.5
assessment_method = "考查"
course_name = "大学英语A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015A"
credit = 5.0
assessment_method = "考试"
course_name = "微积分A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH1009"
credit = 1.0
assessment_method = "考查"
course_name = "机器人与智能装备类专业导论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1002"
credit = 2.0
assessment_method = "考查"
course_name = "军事理论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1003"
credit = 2.0
assessment_method = "考查"
course_name = "军事技能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 0

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001A"
credit = 1.0
assessment_method = "考查"
course_name = "体育A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PSYC1001"
credit = 2.0
assessment_method = "考查"
course_name = "悦己人生—大学生心理健康"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "大学生心理健康教育与咨询中心"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP1009"
credit = 2.0
assessment_method = "考查"
course_name = "计算思维与信息基础"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1013"
credit = 4.0
assessment_method = "考试"
course_name = "电路与电子学"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1014"
credit = 1.0
assessment_method = "考查"
course_name = "电路与电子技术实验"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1016"
credit = 2.5
assessment_method = "考试"
course_name = "中国近现代史纲要"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-1"
credit = 0.5
assessment_method = "考查"
course_name = "形势与政策-1"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1007"
credit = 1.5
assessment_method = "考查"
course_name = "大学英语B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "外语系"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015B"
credit = 5.0
assessment_method = "考试"
course_name = "微积分B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "NESC1001"
credit = 1.0
assessment_method = "考查"
course_name = "国家安全教育"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001B"
credit = 1.0
assessment_method = "考查"
course_name = "体育B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1005A"
credit = 5.0
assessment_method = "考试"
course_name = "大学物理XA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1006A"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验A"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 3
lab = 21
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "22MX44001"
credit = 0.0
assessment_method = "考查"
course_name = "劳动教育概论"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智慧树"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EMEC1002"
credit = 4.0
assessment_method = "考试"
course_name = "理论力学II"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1011"
credit = 3.0
assessment_method = "考试"
course_name = "马克思主义基本原理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1008"
credit = 1.0
assessment_method = "考查"
course_name = "大学英语C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 3.0
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2019"
credit = 3.0
assessment_method = "考试"
course_name = "设计与制造A"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002C"
credit = 0.5
assessment_method = "考查"
course_name = "体育C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1005B"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理XB"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1006B"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验B"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "WRIT0001"
credit = 1.0
assessment_method = "考查"
course_name = "写作与沟通"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "世界文明与对话"
offering_college = "人文与社会科学学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELPA2001"
credit = 3.0
assessment_method = "考查"
course_name = "微电子制造技术"
recommended_year_semester = "第二学年春季"
track = "四选一"
course_nature = "限选"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2007"
credit = 2.0
assessment_method = "考试"
course_name = "流体力学"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 28
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2008"
credit = 3.0
assessment_method = "考查"
course_name = "工程热力学"
recommended_year_semester = "第二学年春季"
track = "四选一"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 42
lab = 6
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENGG1008"
credit = 2.0
assessment_method = "考查"
course_name = "工程训练（制造工艺实习）I"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1018"
credit = 2.5
assessment_method = "考试"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-2"
credit = 1.0
assessment_method = "考查"
course_name = "形势与政策-2"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2020"
credit = 3.0
assessment_method = "考试"
course_name = "设计与制造B"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2021"
credit = 3.0
assessment_method = "考查"
course_name = "动力学与控制"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2022"
credit = 4.0
assessment_method = "考试"
course_name = "固体力学"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 56
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2023"
credit = 3.0
assessment_method = "考查"
course_name = "传感与测试技术"
recommended_year_semester = "第二学年春季"
track = "四选一"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 24
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2024"
credit = 3.0
assessment_method = "考查"
course_name = "机械工程测试技术基础"
recommended_year_semester = "第二学年春季"
track = "四选一"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 24
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002D"
credit = 0.5
assessment_method = "考查"
course_name = "体育D"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "SEIN1054"
credit = 1.0
assessment_method = "考查"
course_name = "项目管理概论"
recommended_year_semester = "第二学年春季"
course_nature = "限选"
course_category = "科学探索与创新"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELPA2002"
credit = 1.0
assessment_method = "考查"
course_name = "认识实习"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 40

[courses.hours]
theory = 0
lab = 0
practice = 1
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "INEP1057"
credit = 1.0
assessment_method = "考查"
course_name = "机械产品创新设计及仿真"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "创新创业实践"
offering_college = "机器人与先进制造学院"
total_hours = 40

[courses.hours]
theory = 0
lab = 0
practice = 1
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2017"
credit = 1.0
assessment_method = "考查"
course_name = "机电科学与技术前沿"
recommended_year_semester = "第二学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH2018"
credit = 1.0
assessment_method = "考查"
course_name = "机器人与智能装备的工程化设计"
recommended_year_semester = "第二学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
