[info]
year = "2025"
major_code = "25L21"
major_name = "工科试验班（卓越优才计划）"
school_name = "基础学部"
plan_ID = "3C2A57135AFD02C6E0630B18F80AFFEB"

[[courses]]
course_code = "CIVL2001"
credit = 1.0
assessment_method = "考查"
course_name = "土木工程专业导论"
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENVR2001"
credit = 1.0
assessment_method = "考查"
course_name = "环境科学与工程专业导论"
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生态环境学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1014"
credit = 2.0
assessment_method = "考查"
course_name = "思想政治理论实践课"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 32

[courses.hours]
theory = 8
lab = 0
practice = 24
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1015"
credit = 2.5
assessment_method = "考查"
course_name = "思想道德与法治"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1017"
credit = 2.5
assessment_method = "考试"
course_name = "习近平新时代中国特色社会主义思想概论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1006"
credit = 1.5
assessment_method = "考查"
course_name = "大学英语A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "外语系"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015A"
credit = 5.0
assessment_method = "考试"
course_name = "微积分A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1002"
credit = 2.0
assessment_method = "考查"
course_name = "军事理论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1003"
credit = 2.0
assessment_method = "考查"
course_name = "军事技能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 120

[courses.hours]
theory = 0
lab = 0
practice = 3
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001A"
credit = 1.0
assessment_method = "考查"
course_name = "体育A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PSYC1001"
credit = 2.0
assessment_method = "考查"
course_name = "悦己人生—大学生心理健康"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "大学生心理健康教育与咨询中心"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "22MX44001"
credit = 0.0
assessment_method = "考查"
course_name = "劳动教育概论"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "CHEM1007"
credit = 2.0
assessment_method = "考查"
course_name = "大学化学II"
recommended_year_semester = "第一学年春季"
track = "材料科学与工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "CHEM1013"
credit = 2.0
assessment_method = "考查"
course_name = "无机化学A"
recommended_year_semester = "第一学年春季"
track = "化学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "CHEM1015A"
credit = 1.5
assessment_method = "考查"
course_name = "分析化学A"
recommended_year_semester = "第一学年春季"
track = "化学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "CHEM1022"
credit = 1.0
assessment_method = "考查"
course_name = "化学前沿导论"
recommended_year_semester = "第一学年春季"
track = "化学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "CIVL1004"
credit = 3.0
assessment_method = "考查"
course_name = "土木制图基础"
recommended_year_semester = "第一学年春季"
track = "土木工程轨道课程包,环境工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 8
tutoring = 0
[[courses]]
course_code = "COMP1009"
credit = 2.0
assessment_method = "考查"
course_name = "计算思维与人工智能"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2011"
credit = 3.0
assessment_method = "考查"
course_name = "计算机语言程序设计"
recommended_year_semester = "第一学年春季"
track = "数字经济轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 48

[courses.hours]
theory = 30
lab = 18
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ECON3063"
credit = 2.0
assessment_method = "考查"
course_name = "商业伦理"
recommended_year_semester = "第一学年春季"
track = "数字经济轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1019"
credit = 4.0
assessment_method = "考查"
course_name = "电路与电子学II"
recommended_year_semester = "第一学年春季"
track = "能源与动力工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1022"
credit = 1.0
assessment_method = "考查"
course_name = "电路与电子技术实验II"
recommended_year_semester = "第一学年春季"
track = "能源与动力工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EMEC1019"
credit = 1.0
assessment_method = "考查"
course_name = "工程力学专业导论"
recommended_year_semester = "第一学年春季"
track = "工程力学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2001"
credit = 1.0
assessment_method = "考查"
course_name = "能源与动力工程专业导论"
recommended_year_semester = "第一学年春季"
track = "能源与动力工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1016"
credit = 2.5
assessment_method = "考试"
course_name = "中国近现代史纲要"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-1"
credit = 0.5
assessment_method = "考查"
course_name = "形势与政策-1"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1007"
credit = 1.5
assessment_method = "考查"
course_name = "大学英语B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "外语系"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015B"
credit = 5.0
assessment_method = "考试"
course_name = "微积分B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH1003"
credit = 3.0
assessment_method = "考查"
course_name = "工程制图基础"
recommended_year_semester = "第一学年春季"
track = "材料科学与工程轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 16
tutoring = 0
[[courses]]
course_code = "MECH1007"
credit = 2.0
assessment_method = "考查"
course_name = "工程制图基础"
recommended_year_semester = "第一学年春季"
track = "工程力学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 8
tutoring = 0
[[courses]]
course_code = "NESC1001"
credit = 1.0
assessment_method = "考查"
course_name = "国家安全教育"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001B"
credit = 1.0
assessment_method = "考查"
course_name = "体育B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1006A"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验A"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 2
lab = 22
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1007A"
credit = 4.5
assessment_method = "考试"
course_name = "大学物理IA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 72

[courses.hours]
theory = 72
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENGG1002"
credit = 2.0
assessment_method = "考查"
course_name = "工程训练（金工实习）"
recommended_year_semester = "第二学年秋季"
track = "工程力学轨道课程包"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
