[info]
year = "2025"
major_code = "25L04"
major_name = "工科试验班（AI加先进技术领军班深圳拔尖班）"
school_name = "基础学部"
plan_ID = "3C3DD56613293043E0630B18F80AE6AF"

[[courses]]
course_code = "COMP1012"
credit = 3.0
assessment_method = "考查"
course_name = "计算思维与人工智能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1014"
credit = 2.0
assessment_method = "考查"
course_name = "思想政治理论实践课"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 32

[courses.hours]
theory = 8
lab = 0
practice = 24
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1015"
credit = 2.5
assessment_method = "考查"
course_name = "思想道德与法治"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1017"
credit = 2.5
assessment_method = "考试"
course_name = "习近平新时代中国特色社会主义思想概论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1009A"
credit = 2.5
assessment_method = "考查"
course_name = "外语综合A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "英语"
offering_college = "外语系"
total_hours = 60

[courses.hours]
theory = 60
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1011A"
credit = 5.0
assessment_method = "考试"
course_name = "数学分析A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1002"
credit = 2.0
assessment_method = "考查"
course_name = "军事理论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1003"
credit = 2.0
assessment_method = "考查"
course_name = "军事技能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 120

[courses.hours]
theory = 0
lab = 0
practice = 3
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001A"
credit = 1.0
assessment_method = "考查"
course_name = "体育A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PSYC1001"
credit = 2.0
assessment_method = "考查"
course_name = "悦己人生—大学生心理健康"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "大学生心理健康教育与咨询中心"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "22MX44001"
credit = 0.0
assessment_method = "考查"
course_name = "劳动教育概论"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP1015"
credit = 2.0
assessment_method = "考查"
course_name = "计算与智能程序设计"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 0
lab = 0
practice = 32
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1028A"
credit = 3.0
assessment_method = "考试"
course_name = "电路与电子技术A"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1016"
credit = 2.5
assessment_method = "考试"
course_name = "中国近现代史纲要"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-1"
credit = 0.5
assessment_method = "考查"
course_name = "形势与政策-1"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1009B"
credit = 1.5
assessment_method = "考查"
course_name = "外语综合B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "英语"
offering_college = "外语系"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1011B"
credit = 5.0
assessment_method = "考试"
course_name = "数学分析B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "NESC1001"
credit = 1.0
assessment_method = "考查"
course_name = "国家安全教育"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001B"
credit = 1.0
assessment_method = "考查"
course_name = "体育B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1005A"
credit = 5.0
assessment_method = "考试"
course_name = "大学物理XA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1006A"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验A"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 2
lab = 22
practice = 0
exercise = 0
computer = 0
tutoring = 0
