[[courses]]
course_code = "AUTO3001A"
credit = 2.0
assessment_method = "考试"
course_name = "自动控制理论A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3002A"
credit = 3.0
assessment_method = "考试"
course_name = "自动控制实践A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3003"
credit = 2.0
assessment_method = "考查"
course_name = "数字图像处理"
recommended_year_semester = "第一学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 34

[courses.hours]
theory = 24
lab = 10
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "AUTO3004"
credit = 2.5
assessment_method = "考查"
course_name = "系统建模与仿真"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 44

[courses.hours]
theory = 32
lab = 4
practice = 0
exercise = 0
computer = 8
tutoring = 0
[[courses]]
course_code = "AUTO3016"
credit = 1.5
assessment_method = "考查"
course_name = "自动控制实践A实验"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "智能科学与工程学院"
total_hours = 40

[courses.hours]
theory = 0
lab = 40
practice = 0
exercise = 0
computer = 0
tutoring = 0
