[[courses]]
course_code = "BIO1002E"
credit = 2.0
assessment_method = "考查"
course_name = "生命与健康科学"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "医工学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1113E"
credit = 2.0
assessment_method = "考查"
course_name = "中国式现代化：研究与探索"
recommended_year_semester = "第一学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1120E"
credit = 3.0
assessment_method = "考查"
course_name = "初级汉语I"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1124E"
credit = 1.0
assessment_method = "考查"
course_name = "中国典型滨海湿地的退化与保护"
recommended_year_semester = "第一学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 6
lab = 0
practice = 10
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002E"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1110E"
credit = 2.0
assessment_method = "考查"
course_name = "中国概况"
recommended_year_semester = "第一学年秋季,第一学年春季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1119E"
credit = 1.0
assessment_method = "考查"
course_name = "考古与中华文明"
recommended_year_semester = "第一学年秋季,第一学年春季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 12
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1003E"
credit = 4.0
assessment_method = "考试"
course_name = "电路 II"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1004E"
credit = 0.5
assessment_method = "考查"
course_name = "电路实验II"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 12

[courses.hours]
theory = 0
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1121E"
credit = 3.0
assessment_method = "考查"
course_name = "初级汉语 II"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文艺术学系"
total_hours = 48

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 24
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1129E"
credit = 1.0
assessment_method = "考查"
course_name = "中国清洁空气行动与应对气候变化"
recommended_year_semester = "第一学年春季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "生态环境学院"
total_hours = 16

[courses.hours]
theory = 10
lab = 2
practice = 4
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1130E"
credit = 2.0
assessment_method = "考查"
course_name = "中国先进结构建造和监测技术"
recommended_year_semester = "第一学年春季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1019E"
credit = 5.0
assessment_method = "考试"
course_name = "微积分进阶"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1001AE"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理 IA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1002AE"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验 IA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1118E"
credit = 1.0
assessment_method = "考查"
course_name = "中国传统服饰与印染"
recommended_year_semester = "第一学年春季,第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 8
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1111E"
credit = 2.0
assessment_method = "考查"
course_name = "中国文化"
recommended_year_semester = "第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1114E"
credit = 2.0
assessment_method = "考查"
course_name = "中国碳达峰、碳中和目标的实现路径"
recommended_year_semester = "第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "经济管理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1125E"
credit = 2.0
assessment_method = "考查"
course_name = "中国土木工程材料及其结构应用"
recommended_year_semester = "第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "智能土木与海洋工程学院"
total_hours = 32

[courses.hours]
theory = 28
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1126E"
credit = 2.0
assessment_method = "考查"
course_name = "中国制造的复兴之路"
recommended_year_semester = "第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "HUMA1127E"
credit = 1.0
assessment_method = "考查"
course_name = "中国古典园林鉴赏"
recommended_year_semester = "第二学年秋季"
track = "国情类课程"
course_nature = "限选"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 16

[courses.hours]
theory = 10
lab = 6
practice = 0
exercise = 0
computer = 0
tutoring = 0
