[[courses]]
course_code = "ELEC3023"
credit = 2.0
assessment_method = "考查"
course_name = "空间通信"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
