[[courses]]
course_code = "CHEM1007"
credit = 2.0
assessment_method = "考试"
course_name = "大学化学II"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2001"
credit = 1.0
assessment_method = "考查"
course_name = "能源动力类专业导论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1014"
credit = 2.0
assessment_method = "考查"
course_name = "思想政治理论实践课"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 32

[courses.hours]
theory = 8
lab = 0
practice = 24
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1015"
credit = 2.5
assessment_method = "考查"
course_name = "思想道德与法治"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1006"
credit = 2.0
assessment_method = "考查"
course_name = "大学英语A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1002"
credit = 4.0
assessment_method = "考试"
course_name = "代数与几何"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015A"
credit = 5.0
assessment_method = "考试"
course_name = "微积分A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1002"
credit = 2.0
assessment_method = "考查"
course_name = "军事理论"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 36

[courses.hours]
theory = 36
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MILT1003"
credit = 2.0
assessment_method = "考查"
course_name = "军事技能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）（基础学部）｜团委｜武装部"
total_hours = 0

[courses.hours]
theory = 80
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001A"
credit = 1.0
assessment_method = "考查"
course_name = "体育A"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP1008"
credit = 2.0
assessment_method = "考试"
course_name = "C语言程序设计I"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 20
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP1009"
credit = 2.0
assessment_method = "考查"
course_name = "计算思维与信息基础"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1016"
credit = 2.5
assessment_method = "考试"
course_name = "中国近现代史纲要"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1017"
credit = 2.5
assessment_method = "考查"
course_name = "习近平新时代中国特色社会主义思想概论"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "LANG1007"
credit = 2.0
assessment_method = "考查"
course_name = "大学英语B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1015B"
credit = 5.0
assessment_method = "考试"
course_name = "微积分B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 80

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MECH1007"
credit = 2.0
assessment_method = "考试"
course_name = "工程制图基础"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 8
tutoring = 0
[[courses]]
course_code = "NESC1001"
credit = 1.0
assessment_method = "考查"
course_name = "国家安全教育"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1001B"
credit = 1.0
assessment_method = "考查"
course_name = "体育B"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1001A"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理IA"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER3044"
credit = 1.0
assessment_method = "考查"
course_name = "认识实习"
recommended_year_semester = "第一学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 0

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EMEC1003"
credit = 2.0
assessment_method = "考试"
course_name = "理论力学III"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EMEC1004"
credit = 0.5
assessment_method = "考查"
course_name = "工程力学实验（理力）"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 8

[courses.hours]
theory = 0
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2002"
credit = 2.5
assessment_method = "考试"
course_name = "热力学"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 40

[courses.hours]
theory = 34
lab = 6
practice = 0
exercise = 8
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1011"
credit = 3.0
assessment_method = "考试"
course_name = "马克思主义基本原理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 3.0
assessment_method = "考查"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1005"
credit = 2.5
assessment_method = "考试"
course_name = "复变函数与积分变换"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002C"
credit = 0.5
assessment_method = "考查"
course_name = "体育C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1001B"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理IB"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1002A"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验IA"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 3
lab = 21
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EMEC1006"
credit = 2.0
assessment_method = "考试"
course_name = "材料力学II"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2003"
credit = 3.0
assessment_method = "考试"
course_name = "传热学"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 48

[courses.hours]
theory = 42
lab = 6
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENER2004"
credit = 5.0
assessment_method = "考试"
course_name = "流体力学"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 80

[courses.hours]
theory = 70
lab = 10
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENGG1002"
credit = 2.0
assessment_method = "考查"
course_name = "工程训练（金工实习）"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 80

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1018"
credit = 2.5
assessment_method = "考试"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002D"
credit = 0.5
assessment_method = "考查"
course_name = "体育D"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1002B"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验IB"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
