[info]
year = "2020"
major_code = "010102"
major_name = "计算机科学与技术（第二学士学位）"
school_name = "计算机科学与技术学院"
plan_ID = "ADAF2CFE5CC953A3E0530B18F80A5512"

[[courses]]
course_code = "COMP2007"
credit = 2.5
assessment_method = "考试"
course_name = "算法设计与分析"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2019"
credit = 4.0
assessment_method = "考试"
course_name = "数字逻辑设计"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 44
lab = 20
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2023"
credit = 2.0
assessment_method = "考试"
course_name = "汇编语言程序设计"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3001"
credit = 4.0
assessment_method = "考试"
course_name = "操作系统"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 40
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3002"
credit = 2.0
assessment_method = "考试"
course_name = "软件工程"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3003"
credit = 3.5
assessment_method = "考试"
course_name = "计算机网络"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 56

[courses.hours]
theory = 44
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3005"
credit = 2.5
assessment_method = "考试"
course_name = "人工智能"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 32
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3040"
credit = 2.5
assessment_method = "考查"
course_name = "密码学基础"
recommended_year_semester = "第一学年秋季"
track = "方向选修课模块-网络与信息安全方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 24
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3044"
credit = 2.0
assessment_method = "考查"
course_name = "科研写作交流技巧"
recommended_year_semester = "第一学年秋季"
track = "方向选修课模块-智能计算方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3009"
credit = 2.0
assessment_method = "考查"
course_name = "大数据导论"
recommended_year_semester = "第一学年秋季,第二学年秋季"
track = "方向选修课模块-智能计算方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 28
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3043"
credit = 2.0
assessment_method = "考查"
course_name = "深度学习体系结构"
recommended_year_semester = "第一学年秋季,第二学年秋季"
track = "方向选修课模块-计算机系统方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2008"
credit = 4.0
assessment_method = "考试"
course_name = "计算机组成原理"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 52
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3010"
credit = 3.0
assessment_method = "考试"
course_name = "数据库系统"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3011"
credit = 3.5
assessment_method = "考试"
course_name = "计算机体系结构"
recommended_year_semester = "第一学年春季"
track = "方向选修课模块-计算机系统方向"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 56

[courses.hours]
theory = 40
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3031"
credit = 2.0
assessment_method = "考查"
course_name = "WEB信息处理"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3032"
credit = 2.5
assessment_method = "考查"
course_name = "网络安全"
recommended_year_semester = "第一学年春季"
track = "方向选修课模块-网络与信息安全方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 16
tutoring = 0
[[courses]]
course_code = "COMP3017"
credit = 2.0
assessment_method = "考查"
course_name = "服务计算"
recommended_year_semester = "第一学年春季,第二学年秋季"
track = "方向选修课模块-计算机系统方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3026"
credit = 2.0
assessment_method = "考查"
course_name = "分布式系统"
recommended_year_semester = "第一学年春季,第二学年秋季"
track = "方向选修课模块-计算机系统方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3016"
credit = 2.5
assessment_method = "考查"
course_name = "计算机系统安全"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "网络与信息安全领域"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 40

[courses.hours]
theory = 32
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3019"
credit = 2.0
assessment_method = "考查"
course_name = "生物信息学"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-智能计算方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3021"
credit = 2.0
assessment_method = "考查"
course_name = "自然语言处理"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-智能计算方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3023"
credit = 2.0
assessment_method = "考查"
course_name = "物联网导论"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-网络与信息安全方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3028"
credit = 2.0
assessment_method = "考查"
course_name = "软件体系结构"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-计算机系统方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 24
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3029"
credit = 1.5
assessment_method = "考查"
course_name = "计算机视觉"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-智能计算方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3039"
credit = 2.0
assessment_method = "考查"
course_name = "嵌入式计算"
recommended_year_semester = "第一学年春季,第二学年春季"
track = "方向选修课模块-计算机系统方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 22
lab = 10
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2010"
credit = 2.0
assessment_method = "考查"
course_name = "近世代数"
recommended_year_semester = "第二学年秋季"
track = "计算机理论领域"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3004"
credit = 2.0
assessment_method = "考查"
course_name = "形式语言与自动机"
recommended_year_semester = "第二学年秋季"
track = "计算机理论领域"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3006"
credit = 3.0
assessment_method = "考查"
course_name = "机器学习概论"
recommended_year_semester = "第二学年秋季"
track = "人工智能领域"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3007"
credit = 2.0
assessment_method = "考查"
course_name = "模式识别"
recommended_year_semester = "第二学年秋季"
track = "人工智能领域"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3013"
credit = 3.0
assessment_method = "考查"
course_name = "编译原理"
recommended_year_semester = "第二学年秋季"
track = "计算机理论领域"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3014"
credit = 2.0
assessment_method = "考查"
course_name = "信息安全概论"
recommended_year_semester = "第二学年秋季"
track = "网络与信息安全领域"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3018"
credit = 2.0
assessment_method = "考查"
course_name = "图像处理"
recommended_year_semester = "第二学年秋季"
track = "方向选修课模块-智能计算方向"
course_nature = "选修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3020"
credit = 2.0
assessment_method = "考查"
course_name = "信息论"
recommended_year_semester = "第二学年春季"
track = "方向选修课模块-网络与信息安全方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3042"
credit = 2.0
assessment_method = "考查"
course_name = "智能证券投资"
recommended_year_semester = "第二学年春季"
track = "方向选修课模块-智能计算方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 32

[courses.hours]
theory = 22
lab = 10
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3099"
credit = 10.0
assessment_method = "考查"
course_name = "毕业设计（论文）"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 0

[courses.hours]
theory = 560
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP3052"
credit = 3.0
assessment_method = "考查"
course_name = "计算机系统"
recommended_year_semester = "第三学年夏季"
track = "方向选修课模块-计算机系统方向"
course_nature = "限选"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
